#! /bin/sh

sxhkd &
compton -b
polybar --reload top &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme     alternate
bspc config external_rules_command "~/.config/bspwm/rules"

bspc rule -a Gimp state=floating follow=on
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-center /home/enzo/Images/firewatch.jpg

octopi-notifier

# sxiv /home/enzo/Images/firewatch.jpg
# xwinwrap -ov -d -fs -- animate -window WID "/home/enzo/Images/gifs/test.gif"'[1366x768]'
# xwinwrap -ov -d -fs -- animate -limit memory 16MiB -limit map 32MiB -window WID "/home/enzo/Images/gifs/$(ls -1 /home/enzo/Images/gifs | sort -R | head -n1)"'[1366x768]'

# /home/enzo/.config/bspwm/background &
